a="Gauri Gandhi"
print(a)
print(len(a))
print(a.upper())
print(a.lower())
print(a.replace("G","c"))
print(a.split(" "))
print(a.find("G"))
print(a.count("a"))
print(a.index("a"))
print(a.isalpha())
print(a.isalnum())
print(a.isdigit())
print(a.isspace())
print(a.startswith("G"))
print(a.endswith("i"))
print(a.title())
print(a.capitalize())
print(a.swapcase())
print(a.center(20))
print(a.ljust(20))
print(a.rjust(20))
print(a.lstrip())
print(a.rstrip())
print(a.strip())
print(a.isprintable())
